platform :ios, '8.0'
  use_frameworks!

target 'CCContinuousGlucose_Example' do
  pod 'CCContinuousGlucose', :path => '../'
  pod 'CCBluetooth', :git => 'https://github.com/uhnmdi/CCBluetooth.git'
  pod 'CCToolbox', :git => 'https://github.com/uhnmdi/CCToolbox.git'
  pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git'

  target 'CCContinuousGlucose_Tests' do
    inherit! :search_paths
    pod 'CCContinuousGlucose', :path => '../'
  end
end
